@startuml
actor HR as "HR Advisor"

rectangle Database

rectangle "HR System" {
    usecase UC6 as "View an employee's details"

    usecase UCa as "View employee details"

    HR - UC6
    UC6 ..> UCa : include
    UC6 - Database
}
@enduml