@startuml
actor HR as "HR Advisor"
actor DM as "Department Manager"

rectangle Database

rectangle "HR System" {
    usecase UC1 as "Get all salaries"

    usecase UCa as "Print Salaries"

    HR - UC1
    UC1 ..> UCa : include
    UC1 - Database
}
@enduml